workflows:
  ios-build:
    name: iOS Build Workflow
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app using .xcodeproj
        script: |
          xcodebuild clean build \
            -project HelloSwiftUI.xcodeproj \
            -scheme HelloSwiftUI \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/**/*.app
      - build/**/*.ipa
